# Generated by Django 4.2.1 on 2023-05-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cms_img', models.ImageField(upload_to='slider_img/')),
                ('cms_title', models.CharField(max_length=200, verbose_name='Title')),
                ('cms_text', models.CharField(max_length=400, verbose_name='Text')),
                ('cms_css', models.CharField(default='-', max_length=200, verbose_name='CSS class')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
