# Generated by Django 4.2.1 on 2023-05-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tb_token', models.CharField(max_length=200, verbose_name='Token')),
                ('tb_chat', models.CharField(max_length=200, verbose_name='Chat ID')),
                ('tb_text', models.TextField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
